### ISSUE TITLE
Axios Network Error

### ISSUE THREAD

**Issue by iT-Boyer** [dompling/boxjs.react#2]
![截屏2024-01-25 10 27 18](https://github.com/dompling/boxjs.react/assets/4022953/984e2b43-3b9a-454d-9f8f-a3de47da77ab)

**Comment by dompling** [comment]
@iT-Boyer 看起来好像是你的代理软件和 boxjs 没有连接上。

**Comment by iT-Boyer** [comment]
http://boxjs.com 可以正常访问。在 shadowrocket 中配置了boxjs.net,boxjs.com 域名支持 https 解密和安装证书之后正常了。

**Comment by dompling** [comment]
@iT-Boyer 好的
